targets:
  $default:
    sources:
      - "lib/**"
      - "$package$"
    builders:
      velix_ui|command_builder:
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**.g.dart
      velix|registry_builder:
        enabled: true
        options:
          package: "velix_editor/"
        generate_for:
          - lib/*.dart
          - lib/**/*.dart
          - "!lib/*.g.dart"
          - "!lib/**/*.g.dart"
          - "!lib/**/*.part.dart"
          - "!lib/**/*.freezed.dart"
          - "!lib/**/*.gr.dart"
          - "!lib/combined_registry.dart"
      velix|registry_aggregator:
        enabled: true
        options:
          prefix: "lib"
          function_name: "registerEditorTypes"
        generate_for:
          - lib/editor.dart

      velix|registry_json_builder:
        generate_for:
          - lib/*.dart
          - lib/**/*.dart
          - "!lib/**/*.g.dart"
          - "!lib/**/*.part.dart"
      velix|registry_json_aggregator:
        options:
          package: "velix_editor/"
        generate_for:
          - lib/editor.dart
  test:
    sources:
      - test/**.dart
      - $package$
    builders:
      velix|registry_json_builder:
        generate_for:
          - test/*.dart
          - test/**/*.dart
          - "!test/**/*.g.dart"
          - "!test/**/*.part.dart"
      velix|registry_json_aggregator:
        options:
          prefix: "test"
          package: "velix_editor/"
        generate_for:
          - test/action_test.dart
      velix|registry_builder:
        generate_for:
          - test/*.dart
          - test/**/*.dart
          - "!test/**/*.g.dart"
          - "!test/**/*.part.dart"
      velix|registry_aggregator:
        options:
          prefix: "test"
        generate_for:
          - test/action_test.dart
