name: velix_editor
description: "Velix Wysiwyg UI editor and runtime engine based on a JSON persistence format including reflection based evaluation of dart expressions."

homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

resolution: workspace
version: 0.9.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.8"

dependencies:
  build_runner: ^2.4.7
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter:
    sdk: flutter
  provider: ^6.0.0
  build: ^3.0.0
  cupertino_icons: ^1.0.8
  velix: ^0.91.3
  velix_di: ^1.1.1
  velix_mapper: ^1.2.1
  velix_i18n: ^1.2.0
  velix_ui: ^1.3.0
  flutter_svg: ^2.1.1
  petitparser: ^7.0.1
  file_picker: ^8.0.0
  uuid: ^4.3.3
  oktoast: ^3.4.0
  file_selector: ^1.0.4
  flutter_highlight: ^0.7.0
  path_provider_platform_interface: ^2.1.0
  file_selector_platform_interface: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  glob: ^2.1.3

flutter:
  assets:
    - assets/icons/
    - assets/icons/widget/
    - assets/locales/en/
    - assets/locales/de/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true