include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    curly_braces_in_flow_control_structures: false
    prefer_function_declarations_over_variables: false
    use_super_parameters: false
    non_constant_identifier_names: false
    type_literal_in_constant_pattern: false