builders:
  type_builder:
    import: "package:velix/src/generators/type_generator.dart"
    builder_factories: [ "typeBuilder" ]
    build_extensions: { "$lib$": [ ".type_registry.g.dart" ] }
    auto_apply: root_package
    build_to: source

targets:
  $default:
    builders:
      velix|type_builder:
        generate_for:
          include:
            - test/main.dart