name: velix
description: "flutter foundation library including validation, a reflection based mapper and automatic two-way form binding ."
version: 0.16.1

homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.8"

dependencies:
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.20.2
  source_gen: ^3.0.0
  analyzer: '^8.0.0'
  build: ^3.0.0
  glob: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  assets:
    - assets/locales/en/velix.json
    - assets/locales/de/velix.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true

