name: velix_workspace
publish_to: none
description: "flutter foundation library including validation, a reflection based mapper and automatic two-way form binding ."
homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^6.0.0
  melos: ^7.1.0

sdkPath: auto
useFlutterCli: true

bootstrap:
  runPubGetInRoot: false

workspace:
  - packages/velix
  - packages/velix_di
  - packages/velix_i18n
  - packages/velix_mapper
  - packages/velix_ui

scripts:
  test:
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in every package that has a test directory