name: velix_workspace
publish_to: none
description: "flutter foundation library including validation, a reflection based mapper and automatic two-way form binding ."
homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

environment:
  sdk: ^3.9.0

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^6.0.0
  melos: ^7.3.0

melos:
  sdkPath: auto
  useFlutterCli: true
  useRootAsPackage: false 
  bootstrap:
    runPubGetInRoot: false

  scripts:
    bootstrap:
      run: flutter pub get
      run_in: all
    test:
      run: melos exec --dir-exists=test -- "flutter test"
      description: Run `flutter test` in every package that has a test directory
    

workspace:
  - packages/velix
  - packages/velix_di
  - packages/velix_i18n
  - packages/velix_mapper
  - packages/velix_ui
  - packages/velix_editor
  - packages/velix_editor/example
  - packages/velix_editor/app
  - examples/example

