builders:
  command_builder:
    import: "package:velix_ui/src/generators/command_generator.dart"
    builder_factories: [ "commandBuilder" ]
    build_extensions: { ".dart": [ ".command.g.dart" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]