name: velix_ui
description: "flutter automatic two-way form binding ."
version: 0.9.1

homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  stack_trace: ^1.10.0
  path: ^1.9.1
  provider: ^6.0.0
  intl: ^0.20.2
  source_gen: ^3.0.0
  analyzer: '^8.0.0'
  build: ^3.0.0
  glob: ^2.1.3
  velix: ^0.9.2
  velix_i18n: ^0.9.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  lints: ^6.0.0

