// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder

part of 'velix_di.dart';


void registerVelixDescriptors() {
  type<ConfigurationManager>(
    location: 'package:velix_di/configuration/configuration.dart:29:1',
    annotations: [
      Injectable(factory: false)
    ],
    constructor: () => ConfigurationManager(),
    fromArrayConstructor: (List<dynamic> args) => ConfigurationManager(),
  );

  var ConfigurationSourceDescriptor =  type<ConfigurationSource>(
    location: 'package:velix_di/configuration/configuration.dart:137:1',
    annotations: [
      Injectable(factory: false)
    ],
    isAbstract: true,
    methods: [
      method<ConfigurationSource,void>('setManager',
        annotations: [
          Inject()
        ],
        parameters: [
          param<ConfigurationManager>('manager', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConfigurationSource).setManager(args[1])
      )
    ],
  );

  type<SingletonScope>(
    location: 'package:velix_di/di/di.dart:195:1',
    annotations: [
      Scope(name: "singleton", register: false)
    ],
    constructor: () => SingletonScope(),
    fromArrayConstructor: (List<dynamic> args) => SingletonScope(),
  );

  type<EnvironmentScope>(
    location: 'package:velix_di/di/di.dart:215:1',
    annotations: [
      Scope(name: "environment", register: false)
    ],
    constructor: () => EnvironmentScope(),
    fromArrayConstructor: (List<dynamic> args) => EnvironmentScope(),
  );

  type<RequestScope>(
    location: 'package:velix_di/di/di.dart:222:1',
    annotations: [
      Scope(name: "request", register: false)
    ],
    constructor: () => RequestScope(),
    fromArrayConstructor: (List<dynamic> args) => RequestScope(),
  );

  type<OnInjectProcessor>(
    location: 'package:velix_di/di/di.dart:499:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnInjectProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnInjectProcessor(),
  );

  type<OnInitProcessor>(
    location: 'package:velix_di/di/di.dart:504:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnInitProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnInitProcessor(),
  );

  type<OnRunningProcessor>(
    location: 'package:velix_di/di/di.dart:509:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnRunningProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnRunningProcessor(),
  );

  type<OnDestroyProcessor>(
    location: 'package:velix_di/di/di.dart:514:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnDestroyProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnDestroyProcessor(),
  );

  type<Boot>(
    location: 'package:velix_di/di/di.dart:1459:1',
    annotations: [
      Module()
    ],
    constructor: () => Boot(),
    fromArrayConstructor: (List<dynamic> args) => Boot(),
  );

  type<ConfigurationValues>(
    location: 'package:velix_di/configuration/configuration.dart:149:1',
    superClass: ConfigurationSourceDescriptor,
    annotations: [
      Injectable(factory: false)
    ],
    params: [
      param<Map<String, dynamic>>('values', isRequired: true)
    ],
    constructor: ({required Map<String, dynamic> values}) => ConfigurationValues(values),
    fromArrayConstructor: (List<dynamic> args) => ConfigurationValues(args[0] as Map<String, dynamic>),
  );

  type<JsonFileConfigurationSource>(
    location: 'package:velix_di/configuration/source/json_source.dart:7:1',
    superClass: ConfigurationSourceDescriptor,
    annotations: [
      Injectable(factory: false)
    ],
    params: [
      param<String>('filePath', isRequired: true)
    ],
    constructor: ({String filePath = ''}) => JsonFileConfigurationSource(filePath),
    fromArrayConstructor: (List<dynamic> args) => JsonFileConfigurationSource(args[0] as String),
  );

}
