// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

part of 'velix_di.dart';


void registerVelixDescriptors() {
  type<ConfigurationManager>(
    location: 'package:velix_di/configuration/configuration.dart:32:1',
    annotations: [
      Injectable(factory: false)
    ],
    constructor: () => ConfigurationManager(),
    fromMapConstructor: (Map<String,dynamic> args) => ConfigurationManager(),
    fromArrayConstructor: (List<dynamic> args) => ConfigurationManager(),
  );

  var configurationSourceDescriptor =  type<ConfigurationSource>(
    location: 'package:velix_di/configuration/configuration.dart:140:1',
    annotations: [
      Injectable(factory: false)
    ],
    isAbstract: true,
    methods: [
      method<ConfigurationSource,void>('setManager',
        annotations: [
          Inject()
        ],
        parameters: [
          param<ConfigurationManager>('manager', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConfigurationSource).setManager(args[1])
      )
    ],
  );

  type<SingletonScope>(
    location: 'package:velix_di/di/di.dart:201:1',
    annotations: [
      Scope(name: "singleton", register: false)
    ],
    constructor: () => SingletonScope(),
    fromMapConstructor: (Map<String,dynamic> args) => SingletonScope(),
    fromArrayConstructor: (List<dynamic> args) => SingletonScope(),
  );

  type<EnvironmentScope>(
    location: 'package:velix_di/di/di.dart:222:1',
    annotations: [
      Scope(name: "environment", register: false)
    ],
    constructor: () => EnvironmentScope(),
    fromMapConstructor: (Map<String,dynamic> args) => EnvironmentScope(),
    fromArrayConstructor: (List<dynamic> args) => EnvironmentScope(),
  );

  type<RequestScope>(
    location: 'package:velix_di/di/di.dart:230:1',
    annotations: [
      Scope(name: "request", register: false)
    ],
    constructor: () => RequestScope(),
    fromMapConstructor: (Map<String,dynamic> args) => RequestScope(),
    fromArrayConstructor: (List<dynamic> args) => RequestScope(),
  );

  type<OnInjectProcessor>(
    location: 'package:velix_di/di/di.dart:520:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnInjectProcessor(),
    fromMapConstructor: (Map<String,dynamic> args) => OnInjectProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnInjectProcessor(),
  );

  type<OnInitProcessor>(
    location: 'package:velix_di/di/di.dart:526:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnInitProcessor(),
    fromMapConstructor: (Map<String,dynamic> args) => OnInitProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnInitProcessor(),
  );

  type<OnRunningProcessor>(
    location: 'package:velix_di/di/di.dart:532:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnRunningProcessor(),
    fromMapConstructor: (Map<String,dynamic> args) => OnRunningProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnRunningProcessor(),
  );

  type<OnDestroyProcessor>(
    location: 'package:velix_di/di/di.dart:538:1',
    annotations: [
      Injectable(eager: false)
    ],
    constructor: () => OnDestroyProcessor(),
    fromMapConstructor: (Map<String,dynamic> args) => OnDestroyProcessor(),
    fromArrayConstructor: (List<dynamic> args) => OnDestroyProcessor(),
  );

  type<Boot>(
    location: 'package:velix_di/di/di.dart:1468:1',
    annotations: [
      Module()
    ],
    constructor: () => Boot(),
    fromMapConstructor: (Map<String,dynamic> args) => Boot(),
    fromArrayConstructor: (List<dynamic> args) => Boot(),
  );

  type<ConfigurationValues>(
    location: 'package:velix_di/configuration/configuration.dart:152:1',
    superClass: configurationSourceDescriptor,
    annotations: [
      Injectable(factory: false)
    ],
    params: [
      param<Map<String, dynamic>>('values', isRequired: true)
    ],
    constructor: ({required Map<String, dynamic> values}) => ConfigurationValues(values),
    fromMapConstructor: (Map<String,dynamic> args) => ConfigurationValues(args['values'] as Map<String, dynamic>),
    fromArrayConstructor: (List<dynamic> args) => ConfigurationValues(args[0] as Map<String, dynamic>),
  );

  type<JsonFileConfigurationSource>(
    location: 'package:velix_di/configuration/source/json_source.dart:7:1',
    superClass: configurationSourceDescriptor,
    annotations: [
      Injectable(factory: false)
    ],
    params: [
      param<String>('filePath', isRequired: true)
    ],
    constructor: ({String filePath = ''}) => JsonFileConfigurationSource(filePath),
    fromMapConstructor: (Map<String,dynamic> args) => JsonFileConfigurationSource(args['filePath'] as String),
    fromArrayConstructor: (List<dynamic> args) => JsonFileConfigurationSource(args[0] as String),
  );

  TypeDescriptor.verify();
}
