// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

import 'package:velix/velix.dart';

void registerTypes() {
  // No annotated classes found
  TypeDescriptor.verify();
}
