// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

import 'package:velix/velix.dart';
import 'conflict/conflict.dart';
import 'cycle/cycle.dart';
import 'di.dart';
import 'mock/mock.dart';
import 'package:velix/reflectable/reflectable.dart';
import 'package:velix_di/configuration/configuration.dart';
import 'package:velix_di/di/di.dart';

void registerTypes() {
  type<ConflictModule>(
    location: 'asset:velix_di/test/conflict/conflict.dart:3:1',
    annotations: [
      Module()
    ],
    constructor: () => ConflictModule(),
    fromMapConstructor: (Map<String,dynamic> args) => ConflictModule(),
    fromArrayConstructor: (List<dynamic> args) => ConflictModule(),
    methods: [
      method<ConflictModule,Conflict>('create',
        annotations: [
          Create()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConflictModule).create()
      )
    ],
  );

  type<Conflict>(
    location: 'asset:velix_di/test/conflict/conflict.dart:11:1',
    annotations: [
      Injectable()
    ],
    constructor: () => Conflict(),
    fromMapConstructor: (Map<String,dynamic> args) => Conflict(),
    fromArrayConstructor: (List<dynamic> args) => Conflict(),
  );

  type<CycleModule>(
    location: 'asset:velix_di/test/cycle/cycle.dart:3:1',
    annotations: [
      Module()
    ],
    constructor: () => CycleModule(),
    fromMapConstructor: (Map<String,dynamic> args) => CycleModule(),
    fromArrayConstructor: (List<dynamic> args) => CycleModule(),
  );

  type<TestModule>(
    location: 'asset:velix_di/test/di.dart:6:1',
    annotations: [
      Module(includeSubdirectories: false)
    ],
    constructor: () => TestModule(),
    fromMapConstructor: (Map<String,dynamic> args) => TestModule(),
    fromArrayConstructor: (List<dynamic> args) => TestModule(),
    methods: [
      method<TestModule,ConfigurationManager>('createConfigurationManager',
        annotations: [
          Create()
        ],
        invoker: (List<dynamic> args)=> (args[0] as TestModule).createConfigurationManager()
      ), 
      method<TestModule,ConfigurationValues>('createConfigurationValues',
        annotations: [
          Create()
        ],
        invoker: (List<dynamic> args)=> (args[0] as TestModule).createConfigurationValues()
      )
    ],
  );

  type<Bar>(
    location: 'asset:velix_di/test/di.dart:25:1',
    annotations: [
      Injectable(scope: "singleton", eager: true)
    ],
    constructor: () => Bar(),
    fromMapConstructor: (Map<String,dynamic> args) => Bar(),
    fromArrayConstructor: (List<dynamic> args) => Bar(),
  );

  type<Baz>(
    location: 'asset:velix_di/test/di.dart:30:1',
    annotations: [
      Injectable(factory: false)
    ],
    constructor: () => Baz(),
    fromMapConstructor: (Map<String,dynamic> args) => Baz(),
    fromArrayConstructor: (List<dynamic> args) => Baz(),
  );

  type<Factory>(
    location: 'asset:velix_di/test/di.dart:44:1',
    annotations: [
      Injectable(scope: "singleton", eager: true)
    ],
    constructor: () => Factory(),
    fromMapConstructor: (Map<String,dynamic> args) => Factory(),
    fromArrayConstructor: (List<dynamic> args) => Factory(),
    methods: [
      method<Factory,void>('onInit',
        annotations: [
          OnInit()
        ],
        parameters: [
          param<Environment>('environment', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).onInit(args[1])
      ), 
      method<Factory,void>('onDestroy',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).onDestroy()
      ), 
      method<Factory,void>('setFoo',
        annotations: [
          Inject()
        ],
        parameters: [
          param<Foo>('foo', isRequired: true), 
          param<int>('value', isRequired: true,
          annotations: [
            Value("foo.bar", defaultValue: 1)
          ],
          )
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).setFoo(args[1], args[2])
      ), 
      method<Factory,Baz>('createBaz',
        annotations: [
          Create()
        ],
        parameters: [
          param<Bar>('bar', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).createBaz(args[1])
      )
    ],
  );

  type<Collections>(
    location: 'asset:velix_di/test/di.dart:70:1',
    params: [
      param<List<Money>>('prices', isNamed: true, isRequired: true)
    ],
    constructor: ({required List<Money> prices}) => Collections(prices: prices),
    fromMapConstructor: (Map<String,dynamic> args) => Collections(prices: args['prices'] as List<Money>),
    fromArrayConstructor: (List<dynamic> args) => Collections(prices: args[0] as List<Money>),
    fields: [
      field<Collections,List<Money>>('prices',
        elementType: Money,
        factoryConstructor: () => <Money>[],
        getter: (obj) => obj.prices,
      )
    ]
  );

  type<Money>(
    location: 'asset:velix_di/test/di.dart:100:1',
    params: [
      param<String>('currency', isNamed: true, isRequired: true), 
      param<int>('value', isNamed: true, isRequired: true)
    ],
    constructor: ({String currency = '', int value = 0}) => Money(currency: currency, value: value),
    fromMapConstructor: (Map<String,dynamic> args) => Money(currency: args['currency'] as String? ?? '', value: args['value'] as int? ?? 0),
    fromArrayConstructor: (List<dynamic> args) => Money(currency: args[0] as String? ?? '', value: args[1] as int? ?? 0),
    fields: [
      field<Money,String>('currency',
        type: StringType().maxLength(7),
        getter: (obj) => obj.currency,
      ), 
      field<Money,int>('value',
        type: IntType().greaterThan(0),
        getter: (obj) => obj.value,
      )
    ]
  );

  var BaseDescriptor =  type<Base>(
    location: 'asset:velix_di/test/di.dart:128:1',
    params: [
      param<String>('name', isRequired: true)
    ],
    constructor: ({String name = ''}) => Base(name),
    fromMapConstructor: (Map<String,dynamic> args) => Base(args['name'] as String),
    fromArrayConstructor: (List<dynamic> args) => Base(args[0] as String),
    fields: [
      field<Base,String>('name',
        getter: (obj) => obj.name,
      )
    ]
  );

  var ConditionalBaseDescriptor =  type<ConditionalBase>(
    location: 'asset:velix_di/test/di.dart:142:1',
    annotations: [
      Injectable()
    ],
    isAbstract: true,
    methods: [
      method<ConditionalBase,void>('initBase',
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConditionalBase).initBase()
      ), 
      method<ConditionalBase,void>('destroyBase',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConditionalBase).destroyBase()
      )
    ],
  );

  var RootTypeDescriptor =  type<RootType>(
    location: 'asset:velix_di/test/di.dart:184:1',
    annotations: [
      Injectable()
    ],
    isAbstract: true,
  );

  type<Types>(
    location: 'asset:velix_di/test/di.dart:194:1',
    params: [
      param<int>('int_var', isNamed: true, isRequired: true), 
      param<double>('double_var', isNamed: true, isRequired: true), 
      param<bool>('bool_var', isNamed: true, isRequired: true), 
      param<String>('string_var', isNamed: true, isRequired: true)
    ],
    constructor: ({int int_var = 0, double double_var = 0.0, bool bool_var = false, String string_var = ''}) => Types(int_var: int_var, double_var: double_var, bool_var: bool_var, string_var: string_var),
    fromMapConstructor: (Map<String,dynamic> args) => Types(int_var: args['int_var'] as int? ?? 0, double_var: args['double_var'] as double? ?? 0.0, bool_var: args['bool_var'] as bool? ?? false, string_var: args['string_var'] as String? ?? ''),
    fromArrayConstructor: (List<dynamic> args) => Types(int_var: args[0] as int? ?? 0, double_var: args[1] as double? ?? 0.0, bool_var: args[2] as bool? ?? false, string_var: args[3] as String? ?? ''),
    fields: [
      field<Types,int>('int_var',
        getter: (obj) => obj.int_var,
      ), 
      field<Types,double>('double_var',
        getter: (obj) => obj.double_var,
      ), 
      field<Types,bool>('bool_var',
        getter: (obj) => obj.bool_var,
      ), 
      field<Types,String>('string_var',
        getter: (obj) => obj.string_var,
      )
    ]
  );

  type<Invoice>(
    location: 'asset:velix_di/test/di.dart:228:1',
    params: [
      param<List<Product>>('products', isNamed: true, isRequired: true), 
      param<DateTime>('date', isNamed: true, isRequired: true)
    ],
    constructor: ({required List<Product> products, required DateTime date}) => Invoice(products: products, date: date),
    fromMapConstructor: (Map<String,dynamic> args) => Invoice(products: args['products'] as List<Product>, date: args['date'] as DateTime),
    fromArrayConstructor: (List<dynamic> args) => Invoice(products: args[0] as List<Product>, date: args[1] as DateTime),
    fields: [
      field<Invoice,DateTime>('date',
        getter: (obj) => obj.date,
      ), 
      field<Invoice,List<Product>>('products',
        elementType: Product,
        factoryConstructor: () => <Product>[],
        getter: (obj) => obj.products,
      )
    ]
  );

  type<Flat>(
    location: 'asset:velix_di/test/di.dart:236:1',
    params: [
      param<String>('id', isNamed: true, isRequired: true), 
      param<String>('priceCurrency', isNamed: true, isRequired: true), 
      param<int>('priceValue', isNamed: true, isRequired: true)
    ],
    constructor: ({String id = '', String priceCurrency = '', int priceValue = 0}) => Flat(id: id, priceCurrency: priceCurrency, priceValue: priceValue),
    fromMapConstructor: (Map<String,dynamic> args) => Flat(id: args['id'] as String? ?? '', priceCurrency: args['priceCurrency'] as String? ?? '', priceValue: args['priceValue'] as int? ?? 0),
    fromArrayConstructor: (List<dynamic> args) => Flat(id: args[0] as String? ?? '', priceCurrency: args[1] as String? ?? '', priceValue: args[2] as int? ?? 0),
    fields: [
      field<Flat,String>('id',
        type: StringType().maxLength(7),
        getter: (obj) => obj.id,
      ), 
      field<Flat,String>('priceCurrency',
        getter: (obj) => obj.priceCurrency,
      ), 
      field<Flat,int>('priceValue',
        getter: (obj) => obj.priceValue,
      )
    ]
  );

  enumeration<Status>(
    name: 'asset:velix_di/test/di.dart.Status',
    values: Status.values
  );

  type<MockModule>(
    location: 'asset:velix_di/test/mock/mock.dart:5:1',
    annotations: [
      Module(imports: [TestModule], includeSubdirectories: false, includeSiblings: false)
    ],
    constructor: () => MockModule(),
    fromMapConstructor: (Map<String,dynamic> args) => MockModule(),
    fromArrayConstructor: (List<dynamic> args) => MockModule(),
  );

  type<Foo>(
    location: 'asset:velix_di/test/di.dart:35:1',
    annotations: [
      Injectable(scope: "environment")
    ],
    params: [
      param<Bar>('bar', isNamed: true, isRequired: true)
    ],
    constructor: ({required Bar bar}) => Foo(bar: bar),
    fromMapConstructor: (Map<String,dynamic> args) => Foo(bar: args['bar'] as Bar),
    fromArrayConstructor: (List<dynamic> args) => Foo(bar: args[0] as Bar),
  );

  type<Mutable>(
    location: 'asset:velix_di/test/di.dart:112:1',
    params: [
      param<String>('id', isNamed: true, isRequired: true), 
      param<Money>('price', isNamed: true, isRequired: true), 
      param<DateTime>('dateTime', isNamed: true, isRequired: true)
    ],
    constructor: ({String id = '', required Money price, required DateTime dateTime}) => Mutable(id: id, price: price, dateTime: dateTime),
    fromMapConstructor: (Map<String,dynamic> args) => Mutable(id: args['id'] as String? ?? '', price: args['price'] as Money, dateTime: args['dateTime'] as DateTime),
    fromArrayConstructor: (List<dynamic> args) => Mutable(id: args[0] as String? ?? '', price: args[1] as Money, dateTime: args[2] as DateTime),
    fields: [
      field<Mutable,String>('id',
        type: StringType().maxLength(7),
        getter: (obj) => obj.id,
        setter: (obj, value) => (obj as Mutable).id = value,
      ), 
      field<Mutable,Money>('price',
        getter: (obj) => obj.price,
        setter: (obj, value) => (obj as Mutable).price = value,
      ), 
      field<Mutable,DateTime>('dateTime',
        type: DateTimeType().optional(),
        getter: (obj) => obj.dateTime,
        setter: (obj, value) => (obj as Mutable).dateTime = value,
        isNullable: true
      )
    ]
  );

  type<Immutable>(
    location: 'asset:velix_di/test/di.dart:252:1',
    params: [
      param<String>('id', isNamed: true, isRequired: true), 
      param<Money>('price', isNamed: true, isRequired: true)
    ],
    constructor: ({String id = '', required Money price}) => Immutable(id: id, price: price),
    fromMapConstructor: (Map<String,dynamic> args) => Immutable(id: args['id'] as String? ?? '', price: args['price'] as Money),
    fromArrayConstructor: (List<dynamic> args) => Immutable(id: args[0] as String? ?? '', price: args[1] as Money),
    fields: [
      field<Immutable,String>('id',
        type: StringType().maxLength(7),
        getter: (obj) => obj.id,
      ), 
      field<Immutable,Money>('price',
        getter: (obj) => obj.price,
      )
    ]
  );

  type<Derived>(
    location: 'asset:velix_di/test/di.dart:135:1',
    superClass: BaseDescriptor,
    params: [
      param<String>('name', isRequired: true), 
      param<int>('number', isNamed: true, isRequired: true)
    ],
    constructor: ({String name = '', int number = 0}) => Derived(name, number: number),
    fromMapConstructor: (Map<String,dynamic> args) => Derived(args['name'] as String, number: args['number'] as int? ?? 0),
    fromArrayConstructor: (List<dynamic> args) => Derived(args[0] as String, number: args[1] as int? ?? 0),
    fields: [
      field<Derived,int>('number',
        getter: (obj) => obj.number,
      )
    ]
  );

  type<ConditionalProd>(
    location: 'asset:velix_di/test/di.dart:157:1',
    superClass: ConditionalBaseDescriptor,
    annotations: [
      Injectable(scope: "request"),
      Conditional(requires: feature("prod"))
    ],
    constructor: () => ConditionalProd(),
    fromMapConstructor: (Map<String,dynamic> args) => ConditionalProd(),
    fromArrayConstructor: (List<dynamic> args) => ConditionalProd(),
    methods: [
      method<ConditionalProd,void>('initProd',
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConditionalProd).initProd()
      ), 
      method<ConditionalProd,void>('destroyProd',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConditionalProd).destroyProd()
      ), 
      method<ConditionalProd,void>('runProd',
        annotations: [
          OnRunning()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ConditionalProd).runProd()
      )
    ],
  );

  type<ConditionalDev>(
    location: 'asset:velix_di/test/di.dart:178:1',
    superClass: ConditionalBaseDescriptor,
    annotations: [
      Injectable(),
      Conditional(requires: feature("dev"))
    ],
    constructor: () => ConditionalDev(),
    fromMapConstructor: (Map<String,dynamic> args) => ConditionalDev(),
    fromArrayConstructor: (List<dynamic> args) => ConditionalDev(),
  );

  type<MockBase>(
    location: 'asset:velix_di/test/mock/mock.dart:9:1',
    superClass: ConditionalBaseDescriptor,
    annotations: [
      Injectable(replace: true)
    ],
    constructor: () => MockBase(),
    fromMapConstructor: (Map<String,dynamic> args) => MockBase(),
    fromArrayConstructor: (List<dynamic> args) => MockBase(),
  );

  type<DerivedType>(
    location: 'asset:velix_di/test/di.dart:189:1',
    superClass: RootTypeDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => DerivedType(),
    fromMapConstructor: (Map<String,dynamic> args) => DerivedType(),
    fromArrayConstructor: (List<dynamic> args) => DerivedType(),
  );

  type<ImmutableProduct>(
    location: 'asset:velix_di/test/di.dart:210:1',
    params: [
      param<String>('name', isNamed: true, isRequired: true), 
      param<Money>('price', isNamed: true, isRequired: true), 
      param<Status>('status', isNamed: true, isRequired: true)
    ],
    constructor: ({String name = '', required Money price, required Status status}) => ImmutableProduct(name: name, price: price, status: status),
    fromMapConstructor: (Map<String,dynamic> args) => ImmutableProduct(name: args['name'] as String? ?? '', price: args['price'] as Money, status: args['status'] as Status),
    fromArrayConstructor: (List<dynamic> args) => ImmutableProduct(name: args[0] as String? ?? '', price: args[1] as Money, status: args[2] as Status),
    fields: [
      field<ImmutableProduct,String>('name',
        getter: (obj) => obj.name,
      ), 
      field<ImmutableProduct,Money>('price',
        getter: (obj) => obj.price,
      ), 
      field<ImmutableProduct,Status>('status',
        getter: (obj) => obj.status,
      )
    ]
  );

  type<Product>(
    location: 'asset:velix_di/test/di.dart:219:1',
    params: [
      param<String>('name', isNamed: true, isRequired: true), 
      param<Money>('price', isNamed: true, isRequired: true), 
      param<Status>('status', isNamed: true, isRequired: true)
    ],
    constructor: ({String name = '', required Money price, required Status status}) => Product(name: name, price: price, status: status),
    fromMapConstructor: (Map<String,dynamic> args) => Product(name: args['name'] as String? ?? '', price: args['price'] as Money, status: args['status'] as Status),
    fromArrayConstructor: (List<dynamic> args) => Product(name: args[0] as String? ?? '', price: args[1] as Money, status: args[2] as Status),
    fields: [
      field<Product,String>('name',
        getter: (obj) => obj.name,
        setter: (obj, value) => (obj as Product).name = value,
      ), 
      field<Product,Money>('price',
        getter: (obj) => obj.price,
        setter: (obj, value) => (obj as Product).price = value,
      ), 
      field<Product,Status>('status',
        getter: (obj) => obj.status,
        setter: (obj, value) => (obj as Product).status = value,
      )
    ]
  );

  type<ImmutableRoot>(
    location: 'asset:velix_di/test/di.dart:80:1',
    params: [
      param<ImmutableProduct>('product', isNamed: true, isRequired: true)
    ],
    constructor: ({required ImmutableProduct product}) => ImmutableRoot(product: product),
    fromMapConstructor: (Map<String,dynamic> args) => ImmutableRoot(product: args['product'] as ImmutableProduct),
    fromArrayConstructor: (List<dynamic> args) => ImmutableRoot(product: args[0] as ImmutableProduct),
    fields: [
      field<ImmutableRoot,ImmutableProduct>('product',
        getter: (obj) => obj.product,
      )
    ]
  );

  type<MutableRoot>(
    location: 'asset:velix_di/test/di.dart:90:1',
    params: [
      param<Product>('product', isNamed: true, isRequired: true)
    ],
    constructor: ({required Product product}) => MutableRoot(product: product),
    fromMapConstructor: (Map<String,dynamic> args) => MutableRoot(product: args['product'] as Product),
    fromArrayConstructor: (List<dynamic> args) => MutableRoot(product: args[0] as Product),
    fields: [
      field<MutableRoot,Product>('product',
        getter: (obj) => obj.product,
      )
    ]
  );

  // watchout: is part of a cycle
  type<CycleSource>(
    location: 'asset:velix_di/test/cycle/cycle.dart:7:1',
    annotations: [
      Injectable()
    ],
    params: [
      param<CycleTarget>('target', isRequired: true)
    ],
    constructor: ({required CycleTarget target}) => CycleSource(target),
    fromMapConstructor: (Map<String,dynamic> args) => CycleSource(args['target'] as CycleTarget),
    fromArrayConstructor: (List<dynamic> args) => CycleSource(args[0] as CycleTarget),
  );

  // watchout: is part of a cycle
  type<CycleTarget>(
    location: 'asset:velix_di/test/cycle/cycle.dart:12:1',
    annotations: [
      Injectable()
    ],
    params: [
      param<CycleSource>('source', isRequired: true)
    ],
    constructor: ({required CycleSource source}) => CycleTarget(source),
    fromMapConstructor: (Map<String,dynamic> args) => CycleTarget(args['source'] as CycleSource),
    fromArrayConstructor: (List<dynamic> args) => CycleTarget(args[0] as CycleSource),
  );

}
