builders:
  registry_json_aggregator:
    import: "package:velix/src/generators/json_builder.dart"
    builder_factories: [ "jsonRegistryAggregator" ]
    build_extensions:
      ".dart": [ ".new_registry.json" ]
    auto_apply: none  #dependents
    build_to: cache
    defaults:
  registry_json_builder:
    import: "package:velix/src/generators/json_builder.dart"
    builder_factories: [ "registryJSONBuilder" ]
    build_extensions:
      ".dart": [ ".new_registry.json" ]
    auto_apply: none  #dependents
    build_to: cache
    defaults:
    #generate_for:
    #  - lib/*.dart
    #  - lib/**/*.dart
    #  - "!lib/**/*.g.dart"
    #  - "!lib/**/*.part.dart"
    #  - "!lib/**/*.freezed.dart"
    #  - "!lib/**/*.gr.dart"
  # Builder for extracting individual class metadata AND code fragments
  registry_builder:
    import: "package:velix/src/generators/registry_generator.dart"
    builder_factories: [ "registryBuilder" ]
    build_extensions:
      ".dart": [ ".registry.json", ".registry.dart" ]
    auto_apply: none  #dependents
    build_to: cache
    defaults:
      #generate_for:
      #  - lib/*.dart
      #  - lib/**/*.dart
      #  - "!lib/**/*.g.dart"
      #  - "!lib/**/*.part.dart"
      #  - "!lib/**/*.freezed.dart"
      #  - "!lib/**/*.gr.dart"

  # Combine all registries
  registry_aggregator:
    import: "package:velix/src/generators/registry_generator.dart"
    builder_factories: [ "registryAggregator" ]
    build_extensions:
      ".dart": [ ".types.g.dart" ]  # Generate .g.dart part file
    auto_apply: none  # manual trigger only
    build_to: source

targets:
  $default:
    sources:
      - example/**
      - $package$
      - lib/**
    builders:
      velix|registry_builder:
        options:
          package: "velix/"
        generate_for:
          - example/*.dart
          - example/**/*.dart
          - "!example/**/*.g.dart"
          - "!example/**/*.part.dart"
      velix|registry_aggregator:
        options:
          prefix: "example"
        generate_for:
          - example/main.dart
  test:
    sources:
      - test/**
      - $package$
      - lib/**
    builders:
      velix|registry_json_builder:
        generate_for:
          - test/*.dart
          - test/**/*.dart
          - "!test/**/*.g.dart"
          - "!test/**/*.part.dart"
      velix|registry_json_aggregator:
        options:
          prefix: "test"
          package: "velix/"
        generate_for:
          - test/type_descriptor_test.dart
      velix|registry_builder:
        options:
          package: "velix/"
        generate_for:
          - test/*.dart
          - test/**/*.dart
          - "!test/**/*.g.dart"
          - "!test/**/*.part.dart"
      velix|registry_aggregator:
        options:
          prefix: "test"
        generate_for:
          - test/type_descriptor_test.dart