builders:
  type_builder:
    import: "package:velix/src/generators/type_generator.dart"
    builder_factories: [ "typeBuilder" ]
    build_extensions: { "$lib$": [ ".type_registry.g.dart" ] }
    auto_apply: none
    build_to: source
    defaults:
      options:
        function_name: "registerAllDescriptors"
        part_of: ""

targets:
  $default:
    builders:
      velix|type_builder:
        options:
          function_name: "registerVelixDescriptors"
          part_of: "velix.dart"
        generate_for:
          include:
            - lib/velix.dart
          exclude:
            - lib/**.g.dart

  test:
    sources:
      - test/**
    builders:
      velix|type_builder:
        generate_for:
          include:
            - test/test.dart
          exclude:
            - test/**.g.dart