builders:
  type_builder:
    import: "package:velix/src/generators/type_generator.dart"
    builder_factories: [ "typeBuilder" ]
    build_extensions: { "$lib$": [ ".type_registry.g.dart" ] }
    auto_apply: none
    build_to: source
    defaults:
      options:
        function_name: "registerAllDescriptors"
        part_of: ""