name: velix
description: "flutter foundation library. This core library contains basic functionality, mainly the meta-data organization and its related code generator used by the different addons. "
version: 0.90.1

homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0
  path: ^1.9.1
  source_gen: ^3.0.0
  analyzer: '^8.0.0'
  build: ^3.0.0
  glob: ^2.1.3

dev_dependencies:
  async: ^2.12.0
  build_runner: ^2.4.7
  lints: ^6.0.0
  #test: ^1.25.0
  flutter_test:
    sdk: flutter
