// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

import 'package:flutter/foundation.dart';
import 'package:velix/velix.dart';
import 'package:velix_ui/databinding/widgets/common/checkbox.dart' show CheckboxAdapter;
import 'package:velix_ui/databinding/valued_widget.dart' show WidgetAdapter;
import 'package:velix_di/di/di.dart' show Injectable, Module, OnInit, OnDestroy;
import 'package:velix_ui/databinding/widgets/common/label.dart' show LabelAdapter;
import 'package:velix_ui/databinding/widgets/common/slider.dart' show SliderAdapter;
import 'package:velix_ui/databinding/widgets/common/switch.dart' show SwitchAdapter;
import 'package:velix_ui/databinding/widgets/cupertino/datepicker.dart' show CupertinoDatePickerAdapter;
import 'package:velix_ui/databinding/widgets/cupertino/slider.dart' show CupertinoSliderAdapter;
import 'package:velix_ui/databinding/widgets/cupertino/switch.dart' show CupertinoSwitchAdapter;
import 'package:velix_ui/databinding/widgets/cupertino/text.dart' show CupertinoTextFieldAdapter;
import 'package:velix_ui/databinding/widgets/material/datepicker.dart' show MaterialDatePickerAdapter;
import 'package:velix_ui/databinding/widgets/material/dropdown.dart' show DropDownAdapter;
import 'package:velix_ui/databinding/widgets/material/text.dart' show MaterialTextFormFieldAdapter;
import 'package:velix_ui/module.dart' show UIModule;

void registerUITypes() {
  type<CheckboxAdapter>(
    location: 'package:velix_ui/databinding/widgets/common/checkbox.dart:10:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.android]),
      Injectable()
    ],
    constructor: () => CheckboxAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => CheckboxAdapter(),
    fromArrayConstructor: (List<dynamic> args) => CheckboxAdapter(),
  );

  type<LabelAdapter>(
    location: 'package:velix_ui/databinding/widgets/common/label.dart:9:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.iOS, TargetPlatform.android, TargetPlatform.macOS]),
      Injectable()
    ],
    constructor: () => LabelAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => LabelAdapter(),
    fromArrayConstructor: (List<dynamic> args) => LabelAdapter(),
  );

  type<SliderAdapter>(
    location: 'package:velix_ui/databinding/widgets/common/slider.dart:9:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.android]),
      Injectable()
    ],
    constructor: () => SliderAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => SliderAdapter(),
    fromArrayConstructor: (List<dynamic> args) => SliderAdapter(),
  );

  type<SwitchAdapter>(
    location: 'package:velix_ui/databinding/widgets/common/switch.dart:9:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.android, TargetPlatform.iOS, TargetPlatform.macOS]),
      Injectable()
    ],
    constructor: () => SwitchAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => SwitchAdapter(),
    fromArrayConstructor: (List<dynamic> args) => SwitchAdapter(),
  );

  type<CupertinoDatePickerAdapter>(
    location: 'package:velix_ui/databinding/widgets/cupertino/datepicker.dart:10:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.iOS, TargetPlatform.macOS]),
      Injectable()
    ],
    constructor: () => CupertinoDatePickerAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => CupertinoDatePickerAdapter(),
    fromArrayConstructor: (List<dynamic> args) => CupertinoDatePickerAdapter(),
  );

  type<CupertinoSliderAdapter>(
    location: 'package:velix_ui/databinding/widgets/cupertino/slider.dart:10:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.iOS, TargetPlatform.macOS]),
      Injectable()
    ],
    constructor: () => CupertinoSliderAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => CupertinoSliderAdapter(),
    fromArrayConstructor: (List<dynamic> args) => CupertinoSliderAdapter(),
  );

  type<CupertinoSwitchAdapter>(
    location: 'package:velix_ui/databinding/widgets/cupertino/switch.dart:10:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.iOS, TargetPlatform.macOS]),
      Injectable()
    ],
    constructor: () => CupertinoSwitchAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => CupertinoSwitchAdapter(),
    fromArrayConstructor: (List<dynamic> args) => CupertinoSwitchAdapter(),
  );

  type<CupertinoTextFieldAdapter>(
    location: 'package:velix_ui/databinding/widgets/cupertino/text.dart:12:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.iOS, TargetPlatform.macOS]),
      Injectable()
    ],
    constructor: () => CupertinoTextFieldAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => CupertinoTextFieldAdapter(),
    fromArrayConstructor: (List<dynamic> args) => CupertinoTextFieldAdapter(),
  );

  type<MaterialDatePickerAdapter>(
    location: 'package:velix_ui/databinding/widgets/material/datepicker.dart:10:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.android]),
      Injectable()
    ],
    constructor: () => MaterialDatePickerAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => MaterialDatePickerAdapter(),
    fromArrayConstructor: (List<dynamic> args) => MaterialDatePickerAdapter(),
  );

  type<DropDownAdapter>(
    location: 'package:velix_ui/databinding/widgets/material/dropdown.dart:9:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.android]),
      Injectable()
    ],
    constructor: () => DropDownAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => DropDownAdapter(),
    fromArrayConstructor: (List<dynamic> args) => DropDownAdapter(),
  );

  type<MaterialTextFormFieldAdapter>(
    location: 'package:velix_ui/databinding/widgets/material/text.dart:11:1',
    annotations: [
      WidgetAdapter(platforms: [TargetPlatform.android]),
      Injectable()
    ],
    constructor: () => MaterialTextFormFieldAdapter(),
    fromMapConstructor: (Map<String,dynamic> args) => MaterialTextFormFieldAdapter(),
    fromArrayConstructor: (List<dynamic> args) => MaterialTextFormFieldAdapter(),
  );

  type<UIModule>(
    location: 'package:velix_ui/module.dart:4:1',
    annotations: [
      Module(imports: [])
    ],
    constructor: () => UIModule(),
    fromMapConstructor: (Map<String,dynamic> args) => UIModule(),
    fromArrayConstructor: (List<dynamic> args) => UIModule(),
    methods: [
      method<UIModule, void>('onInit',
      type: ClassType<void>(),
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as UIModule).onInit()
      ), 
      method<UIModule, void>('onDestroy',
      type: ClassType<void>(),
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as UIModule).onDestroy()
      )
    ],
  );

  TypeDescriptor.verify();
}
