// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

import 'package:velix/velix.dart';
import 'main.dart';
import 'package:velix_di/configuration/configuration.dart';
import 'package:velix_di/di/di.dart';

void registerAllDescriptors() {
  type<TestModule>(
    location: 'asset:velix_di/example/main.dart:6:1',
    annotations: [
      Module(includeSubdirectories: false)
    ],
    constructor: () => TestModule(),
    fromArrayConstructor: (List<dynamic> args) => TestModule(),
    methods: [
      method<TestModule,ConfigurationManager>('createConfigurationManager',
        annotations: [
          Create()
        ],
        invoker: (List<dynamic> args)=> (args[0] as TestModule).createConfigurationManager()
      ), 
      method<TestModule,ConfigurationValues>('createConfigurationValues',
        annotations: [
          Create()
        ],
        invoker: (List<dynamic> args)=> (args[0] as TestModule).createConfigurationValues()
      )
    ],
  );

  var BarDescriptor =  type<Bar>(
    location: 'asset:velix_di/example/main.dart:23:1',
    annotations: [
      Injectable(scope: "singleton", eager: true)
    ],
    constructor: () => Bar(),
    fromArrayConstructor: (List<dynamic> args) => Bar(),
  );

  type<Baz>(
    location: 'asset:velix_di/example/main.dart:28:1',
    annotations: [
      Injectable(factory: false)
    ],
    constructor: () => Baz(),
    fromArrayConstructor: (List<dynamic> args) => Baz(),
  );

  type<Factory>(
    location: 'asset:velix_di/example/main.dart:42:1',
    annotations: [
      Injectable(scope: "singleton", eager: true)
    ],
    constructor: () => Factory(),
    fromArrayConstructor: (List<dynamic> args) => Factory(),
    methods: [
      method<Factory,void>('onInit',
        annotations: [
          OnInit()
        ],
        parameters: [
          param<Environment>('environment', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).onInit(args[1])
      ), 
      method<Factory,void>('onDestroy',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).onDestroy()
      ), 
      method<Factory,void>('setFoo',
        annotations: [
          Inject()
        ],
        parameters: [
          param<Foo>('foo', isRequired: true), 
          param<int>('value', isRequired: true,
          annotations: [
            Value("foo.bar", defaultValue: 1)
          ],
          )
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).setFoo(args[1], args[2])
      ), 
      method<Factory,Baz>('createBaz',
        annotations: [
          Create()
        ],
        parameters: [
          param<Bar>('bar', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as Factory).createBaz(args[1])
      )
    ],
  );

  type<Foo>(
    location: 'asset:velix_di/example/main.dart:33:1',
    annotations: [
      Injectable(scope: "environment")
    ],
    params: [
      param<Bar>('bar', isNamed: true, isRequired: true)
    ],
    constructor: ({required Bar bar}) => Foo(bar: bar),
    fromArrayConstructor: (List<dynamic> args) => Foo(bar: args[0] as Bar),
  );

}
