// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

import 'dart:ui';

import 'package:velix/velix.dart';
import 'package:velix/reflectable/reflectable.dart';
import 'package:velix_di/di/di.dart';
import 'package:velix_editor/commands/command_stack.dart';
import 'package:velix_editor/editor/editor.dart';
import 'package:velix_editor/editor_module.dart';
import 'package:velix_editor/metadata/annotations.dart';
import 'package:velix_editor/metadata/properties/properties.dart';
import 'package:velix_editor/metadata/type_registry.dart';
import 'package:velix_editor/metadata/widget_data.dart';
import 'package:velix_editor/metadata/widgets/button.dart';
import 'package:velix_editor/metadata/widgets/column.dart';
import 'package:velix_editor/metadata/widgets/container.dart';
import 'package:velix_editor/metadata/widgets/grid.dart';
import 'package:velix_editor/metadata/widgets/label.dart';
import 'package:velix_editor/metadata/widgets/row.dart';
import 'package:velix_editor/metadata/widgets/stack.dart';
import 'package:velix_editor/metadata/widgets/switch.dart';
import 'package:velix_editor/metadata/widgets/text.dart';
import 'package:velix_editor/property_panel/editor/bool_editor.dart';
import 'package:velix_editor/property_panel/editor/code_editor.dart';
import 'package:velix_editor/property_panel/editor/color_editor.dart';
import 'package:velix_editor/property_panel/editor/font_editor.dart';
import 'package:velix_editor/property_panel/editor/font_style_editor.dart';
import 'package:velix_editor/property_panel/editor/font_weight_editor.dart';
import 'package:velix_editor/property_panel/editor/int_editor.dart';
import 'package:velix_editor/property_panel/editor/paddding_editor.dart';
import 'package:velix_editor/property_panel/editor/string_editor.dart';
import 'package:velix_editor/property_panel/editor/value_editor.dart';
import 'package:velix_editor/property_panel/editor_builder.dart';
import 'package:velix_editor/property_panel/editor_registry.dart';
import 'package:velix_editor/theme/theme.dart';
import 'package:velix_editor/theme/widget_builder.dart';
import 'package:velix_editor/theme/widgets/button_widget.dart';
import 'package:velix_editor/theme/widgets/column_widget.dart';
import 'package:velix_editor/theme/widgets/container_widget.dart';
import 'package:velix_editor/theme/widgets/grid_widget.dart';
import 'package:velix_editor/theme/widgets/label_widget.dart';
import 'package:velix_editor/theme/widgets/row_widget.dart';
import 'package:velix_editor/theme/widgets/stack_widget.dart';
import 'package:velix_editor/theme/widgets/switch_widget.dart';
import 'package:velix_editor/theme/widgets/text_widget.dart';
import 'package:velix_editor/util/message_bus.dart';
import 'package:velix_i18n/i18n/locale.dart';
import 'package:velix_mapper/mapper/json.dart';

void registerEditorTypes() {
  type<CommandStack>(
    location: 'package:velix_editor/commands/command_stack.dart:11:1',
    annotations: [
      Injectable(scope: "environment", eager: false)
    ],
    constructor: () => CommandStack(),
    fromMapConstructor: (Map<String,dynamic> args) => CommandStack(),
    fromArrayConstructor: (List<dynamic> args) => CommandStack(),
  );

  type<Address>(
    location: 'package:velix_editor/editor/editor.dart:232:1',
    params: [
      param<String>('city', isNamed: true, isRequired: true), 
      param<String>('street', isNamed: true, isRequired: true)
    ],
    constructor: ({String city = '', String street = ''}) => Address(city: city, street: street),
    fromMapConstructor: (Map<String,dynamic> args) => Address(city: args['city'] as String? ?? '', street: args['street'] as String? ?? ''),
    fromArrayConstructor: (List<dynamic> args) => Address(city: args[0] as String? ?? '', street: args[1] as String? ?? ''),
    fields: [
      field<Address,String>('city',
        getter: (obj) => obj.city,
        setter: (obj, value) => (obj as Address).city = value,
      ), 
      field<Address,String>('street',
        getter: (obj) => obj.street,
        setter: (obj, value) => (obj as Address).street = value,
      )
    ],
    methods: [
      method<Address,String>('hello',
        annotations: [
          Inject()
        ],
        parameters: [
          param<String>('message', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as Address).hello(args[1])
      )
    ],
  );

  type<Page>(
    location: 'package:velix_editor/editor/editor.dart:278:1',
    annotations: [
      Injectable()
    ],
    constructor: () => Page(),
    fromMapConstructor: (Map<String,dynamic> args) => Page(),
    fromArrayConstructor: (List<dynamic> args) => Page(),
    fields: [
      field<Page,User>('user',
        getter: (obj) => obj.user,
        setter: (obj, value) => (obj as Page).user = value,
      )
    ],
    methods: [
      method<Page,void>('setup',
        annotations: [
          Inject()
        ],
        invoker: (List<dynamic> args)=> (args[0] as Page).setup()
      )
    ],
  );

  type<EditorScreenState>(
    location: 'package:velix_editor/editor/editor.dart:331:1',
    constructor: () => EditorScreenState(),
    fromMapConstructor: (Map<String,dynamic> args) => EditorScreenState(),
    fromArrayConstructor: (List<dynamic> args) => EditorScreenState(),
    fields: [
      field<EditorScreenState,Environment>('environment',
        getter: (obj) => obj.environment,
      ), 
      field<EditorScreenState,CommandStack>('commandStack',
        getter: (obj) => obj.commandStack,
      ), 
      field<EditorScreenState,bool>('edit',
        getter: (obj) => obj.edit,
        setter: (obj, value) => (obj as EditorScreenState).edit = value,
      ), 
      field<EditorScreenState,LocaleManager>('localeManager',
        getter: (obj) => obj.localeManager,
      )
    ],
    methods: [
      method<EditorScreenState,void>('open',
        annotations: [
          Method()
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditorScreenState).open()
      ), 
      method<EditorScreenState,void>('save',
        annotations: [
          Method()
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditorScreenState).save()
      ), 
      method<EditorScreenState,void>('revert',
        annotations: [
          Method()
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditorScreenState).revert()
      ), 
      method<EditorScreenState,void>('undo',
        annotations: [
          Method()
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditorScreenState).undo()
      ), 
      method<EditorScreenState,void>('play',
        annotations: [
          Method()
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditorScreenState).play()
      )
    ],
  );

  type<EditorModule>(
    location: 'package:velix_editor/editor_module.dart:5:1',
    annotations: [
      Module(imports: [])
    ],
    constructor: () => EditorModule(),
    fromMapConstructor: (Map<String,dynamic> args) => EditorModule(),
    fromArrayConstructor: (List<dynamic> args) => EditorModule(),
    methods: [
      method<EditorModule,void>('onInit',
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditorModule).onInit()
      ), 
      method<EditorModule,void>('onDestroy',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditorModule).onDestroy()
      )
    ],
  );

  type<ColorConvert>(
    location: 'package:velix_editor/metadata/properties/properties.dart:9:1',
    constructor: () => ColorConvert(),
    fromMapConstructor: (Map<String,dynamic> args) => ColorConvert(),
    fromArrayConstructor: (List<dynamic> args) => ColorConvert(),
  );

  type<FontWeightConvert>(
    location: 'package:velix_editor/metadata/properties/properties.dart:26:1',
    constructor: () => FontWeightConvert(),
    fromMapConstructor: (Map<String,dynamic> args) => FontWeightConvert(),
    fromArrayConstructor: (List<dynamic> args) => FontWeightConvert(),
  );

  type<FontStyleConvert>(
    location: 'package:velix_editor/metadata/properties/properties.dart:40:1',
    constructor: () => FontStyleConvert(),
    fromMapConstructor: (Map<String,dynamic> args) => FontStyleConvert(),
    fromArrayConstructor: (List<dynamic> args) => FontStyleConvert(),
  );

  type<Insets>(
    location: 'package:velix_editor/metadata/properties/properties.dart:70:1',
    params: [
      param<int>('left', isNamed: true, isNullable: true, defaultValue: 0), 
      param<int>('top', isNamed: true, isNullable: true, defaultValue: 0), 
      param<int>('right', isNamed: true, isNullable: true, defaultValue: 0), 
      param<int>('bottom', isNamed: true, isNullable: true, defaultValue: 0)
    ],
    constructor: ({int left = 0, int top = 0, int right = 0, int bottom = 0}) => Insets(left: left, top: top, right: right, bottom: bottom),
    fromMapConstructor: (Map<String,dynamic> args) => Insets(left: args['left'] as int? ?? 0, top: args['top'] as int? ?? 0, right: args['right'] as int? ?? 0, bottom: args['bottom'] as int? ?? 0),
    fromArrayConstructor: (List<dynamic> args) => Insets(left: args[0] as int? ?? 0, top: args[1] as int? ?? 0, right: args[2] as int? ?? 0, bottom: args[3] as int? ?? 0),
    fields: [
      field<Insets,int>('left',
        annotations: [
          DeclareProperty(label: "editor:properties.insets.left")
        ],
        getter: (obj) => obj.left,
        setter: (obj, value) => (obj as Insets).left = value,
      ), 
      field<Insets,int>('top',
        annotations: [
          DeclareProperty(label: "editor:properties.insets.top")
        ],
        getter: (obj) => obj.top,
        setter: (obj, value) => (obj as Insets).top = value,
      ), 
      field<Insets,int>('right',
        annotations: [
          DeclareProperty(label: "editor:properties.insets.right")
        ],
        getter: (obj) => obj.right,
        setter: (obj, value) => (obj as Insets).right = value,
      ), 
      field<Insets,int>('bottom',
        annotations: [
          DeclareProperty(label: "editor:properties.insets.bottom")
        ],
        getter: (obj) => obj.bottom,
        setter: (obj, value) => (obj as Insets).bottom = value,
      )
    ],
  );

  type<Font>(
    location: 'package:velix_editor/metadata/properties/properties.dart:110:1',
    params: [
      param<FontWeight>('weight', isNamed: true, isNullable: true, defaultValue: FontWeight.normal), 
      param<FontStyle>('style', isNamed: true, isNullable: true, defaultValue: FontStyle.normal), 
      param<String>('family', isNamed: true, isNullable: true, defaultValue: "Arial"), 
      param<int>('size', isNamed: true, isNullable: true, defaultValue: 16)
    ],
    constructor: ({FontWeight weight = FontWeight.normal, FontStyle style = FontStyle.normal, String family = "Arial", int size = 16}) => Font(weight: weight, style: style, family: family, size: size),
    fromMapConstructor: (Map<String,dynamic> args) => Font(weight: args['weight'] as FontWeight? ?? FontWeight.normal, style: args['style'] as FontStyle? ?? FontStyle.normal, family: args['family'] as String? ?? "Arial", size: args['size'] as int? ?? 16),
    fromArrayConstructor: (List<dynamic> args) => Font(weight: args[0] as FontWeight? ?? FontWeight.normal, style: args[1] as FontStyle? ?? FontStyle.normal, family: args[2] as String? ?? "Arial", size: args[3] as int? ?? 16),
    fields: [
      field<Font,String>('family',
        annotations: [
          DeclareProperty(label: "editor:properties.font.family", editor: FontEditorBuilder)
        ],
        getter: (obj) => obj.family,
        setter: (obj, value) => (obj as Font).family = value,
      ), 
      field<Font,FontWeight>('weight',
        annotations: [
          DeclareProperty(label: "editor:properties.font.weight")
        ],
        getter: (obj) => obj.weight,
        setter: (obj, value) => (obj as Font).weight = value,
      ), 
      field<Font,FontStyle>('style',
        annotations: [
          DeclareProperty(label: "editor:properties.font.style")
        ],
        getter: (obj) => obj.style,
        setter: (obj, value) => (obj as Font).style = value,
      ), 
      field<Font,int>('size',
        annotations: [
          DeclareProperty(label: "editor:properties.font.size")
        ],
        getter: (obj) => obj.size,
        setter: (obj, value) => (obj as Font).size = value,
      )
    ],
  );

  enumeration<ValueType>(
    name: 'package:velix_editor/metadata/properties/properties.dart.ValueType',
    values: ValueType.values
  );

  enumeration<BorderStyle>(
    name: 'package:velix_editor/metadata/properties/properties.dart.BorderStyle',
    values: BorderStyle.values
  );

  type<TypeRegistry>(
    location: 'package:velix_editor/metadata/type_registry.dart:13:1',
    annotations: [
      Injectable()
    ],
    constructor: () => TypeRegistry(),
    fromMapConstructor: (Map<String,dynamic> args) => TypeRegistry(),
    fromArrayConstructor: (List<dynamic> args) => TypeRegistry(),
    methods: [
      method<TypeRegistry,void>('setup',
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as TypeRegistry).setup()
      )
    ],
  );

  var widgetDataDescriptor =  type<WidgetData>(
    location: 'package:velix_editor/metadata/widget_data.dart:6:1',
    annotations: [
      JsonSerializable(discriminatorField: "type")
    ],
    params: [
      param<String>('type', isNamed: true, isRequired: true), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const [])
    ],
    constructor: ({String type = '', List<WidgetData> children = const []}) => WidgetData(type: type, children: children),
    fromMapConstructor: (Map<String,dynamic> args) => WidgetData(type: args['type'] as String? ?? '', children: args['children'] as List<WidgetData>? ?? const []),
    fromArrayConstructor: (List<dynamic> args) => WidgetData(type: args[0] as String? ?? '', children: args[1] as List<WidgetData>? ?? const []),
    fields: [
      field<WidgetData,String>('type',
        getter: (obj) => obj.type,
      ), 
      field<WidgetData,List<WidgetData>>('children',
        annotations: [
          DeclareProperty(group: "general", label: "editor:groups.general", hide: true),
          Json(required: false)
        ],
        elementType: WidgetData,
        factoryConstructor: () => <WidgetData>[],
        getter: (obj) => obj.children,
        setter: (obj, value) => (obj as WidgetData).children = value,
      ), 
      field<WidgetData,WidgetData>('parent',
        annotations: [
          Json(ignore: true)
        ],
        getter: (obj) => obj.parent,
        setter: (obj, value) => (obj as WidgetData).parent = value,
        isNullable: true
      )
    ],
  );

  var propertyEditorBuilderDescriptor =  type<PropertyEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor_builder.dart:9:1',
    annotations: [
      Injectable()
    ],
    isAbstract: true,
    methods: [
      method<PropertyEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as PropertyEditorBuilder).setup(args[1])
      )
    ],
  );

  type<PropertyEditorBuilderFactory>(
    location: 'package:velix_editor/property_panel/editor_registry.dart:6:1',
    annotations: [
      Injectable()
    ],
    constructor: () => PropertyEditorBuilderFactory(),
    fromMapConstructor: (Map<String,dynamic> args) => PropertyEditorBuilderFactory(),
    fromArrayConstructor: (List<dynamic> args) => PropertyEditorBuilderFactory(),
  );

  type<WidgetFactory>(
    location: 'package:velix_editor/theme/theme.dart:7:1',
    annotations: [
      Injectable()
    ],
    constructor: () => WidgetFactory(),
    fromMapConstructor: (Map<String,dynamic> args) => WidgetFactory(),
    fromArrayConstructor: (List<dynamic> args) => WidgetFactory(),
  );

  var widgetBuilderDescriptor =  type<WidgetBuilder>(
    location: 'package:velix_editor/theme/widget_builder.dart:36:1',
    annotations: [
      Injectable(factory: false, eager: false)
    ],
    isAbstract: true,
    methods: [
      method<WidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as WidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<MessageBus>(
    location: 'package:velix_editor/util/message_bus.dart:7:1',
    annotations: [
      Injectable(scope: "environment", eager: false)
    ],
    constructor: () => MessageBus(),
    fromMapConstructor: (Map<String,dynamic> args) => MessageBus(),
    fromArrayConstructor: (List<dynamic> args) => MessageBus(),
  );

  type<User>(
    location: 'package:velix_editor/editor/editor.dart:253:1',
    params: [
      param<String>('name', isNamed: true, isRequired: true), 
      param<Address>('address', isNamed: true, isRequired: true), 
      param<int>('age', isNamed: true, isRequired: true), 
      param<bool>('cool', isNamed: true, isRequired: true)
    ],
    constructor: ({String name = '', required Address address, int age = 0, bool cool = false}) => User(name: name, address: address, age: age, cool: cool),
    fromMapConstructor: (Map<String,dynamic> args) => User(name: args['name'] as String? ?? '', address: args['address'] as Address, age: args['age'] as int? ?? 0, cool: args['cool'] as bool? ?? false),
    fromArrayConstructor: (List<dynamic> args) => User(name: args[0] as String? ?? '', address: args[1] as Address, age: args[2] as int? ?? 0, cool: args[3] as bool? ?? false),
    fields: [
      field<User,String>('name',
        getter: (obj) => obj.name,
        setter: (obj, value) => (obj as User).name = value,
      ), 
      field<User,int>('age',
        getter: (obj) => obj.age,
        setter: (obj, value) => (obj as User).age = value,
      ), 
      field<User,Address>('address',
        getter: (obj) => obj.address,
        setter: (obj, value) => (obj as User).address = value,
      ), 
      field<User,bool>('cool',
        getter: (obj) => obj.cool,
        setter: (obj, value) => (obj as User).cool = value,
      )
    ],
    methods: [
      method<User,String>('hello',
        annotations: [
          Inject()
        ],
        parameters: [
          param<String>('message', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as User).hello(args[1])
      )
    ],
  );

  type<Value>(
    location: 'package:velix_editor/metadata/properties/properties.dart:61:1',
    params: [
      param<ValueType>('type', isNamed: true, isRequired: true), 
      param<String>('value', isNamed: true, isRequired: true)
    ],
    constructor: ({required ValueType type, required String value}) => Value(type: type, value: value),
    fromMapConstructor: (Map<String,dynamic> args) => Value(type: args['type'] as ValueType, value: args['value'] as String),
    fromArrayConstructor: (List<dynamic> args) => Value(type: args[0] as ValueType, value: args[1] as String),
    fields: [
      field<Value,ValueType>('type',
        getter: (obj) => obj.type,
        setter: (obj, value) => (obj as Value).type = value,
      ), 
      field<Value,String>('value',
        getter: (obj) => obj.value,
        setter: (obj, value) => (obj as Value).value = value,
      )
    ],
  );

  type<Border>(
    location: 'package:velix_editor/metadata/properties/properties.dart:96:1',
    params: [
      param<Color>('color', isNamed: true, isRequired: true), 
      param<int>('width', isNamed: true, isRequired: true), 
      param<BorderStyle>('style', isNamed: true, isRequired: true)
    ],
    constructor: ({required Color color, int width = 0, required BorderStyle style}) => Border(color: color, width: width, style: style),
    fromMapConstructor: (Map<String,dynamic> args) => Border(color: args['color'] as Color, width: args['width'] as int? ?? 0, style: args['style'] as BorderStyle),
    fromArrayConstructor: (List<dynamic> args) => Border(color: args[0] as Color, width: args[1] as int? ?? 0, style: args[2] as BorderStyle),
    fields: [
      field<Border,Color>('color',
        annotations: [
          DeclareProperty(label: "editor:properties.border.color")
        ],
        getter: (obj) => obj.color,
        setter: (obj, value) => (obj as Border).color = value,
      ), 
      field<Border,int>('width',
        annotations: [
          DeclareProperty(label: "editor:properties.border.width")
        ],
        getter: (obj) => obj.width,
        setter: (obj, value) => (obj as Border).width = value,
      ), 
      field<Border,BorderStyle>('style',
        annotations: [
          DeclareProperty(label: "editor:properties.border.style")
        ],
        getter: (obj) => obj.style,
        setter: (obj, value) => (obj as Border).style = value,
      )
    ],
  );

  type<ButtonWidgetData>(
    location: 'package:velix_editor/metadata/widgets/button.dart:10:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "button", group: "widgets", icon: "widget_button"),
      JsonSerializable(discriminator: "button", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "button"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const []), 
      param<String>('label', isNamed: true, isRequired: true), 
      param<Font>('font', isNamed: true, isNullable: true, defaultValue: null), 
      param<Color>('color', isNamed: true, isNullable: true, defaultValue: null), 
      param<Insets>('padding', isNamed: true, isNullable: true, defaultValue: null), 
      param<String>('onClick', isNamed: true, isNullable: true, defaultValue: null)
    ],
    constructor: ({String type = "button", List<WidgetData> children = const [], String label = '', required Font font, required Color color, required Insets padding, String onClick = ''}) => ButtonWidgetData(type: type, children: children, label: label, font: font, color: color, padding: padding, onClick: onClick),
    fromMapConstructor: (Map<String,dynamic> args) => ButtonWidgetData(type: args['type'] as String? ?? "button", children: args['children'] as List<WidgetData>? ?? const [], label: args['label'] as String? ?? '', font: args['font'] as Font?, color: args['color'] as Color?, padding: args['padding'] as Insets?, onClick: args['onClick'] as String? ?? ''),
    fromArrayConstructor: (List<dynamic> args) => ButtonWidgetData(type: args[0] as String? ?? "button", children: args[1] as List<WidgetData>? ?? const [], label: args[2] as String? ?? '', font: args[3] as Font?, color: args[4] as Color?, padding: args[5] as Insets?, onClick: args[6] as String? ?? ''),
    fields: [
      field<ButtonWidgetData,String>('label',
        annotations: [
          DeclareProperty(group: "general")
        ],
        getter: (obj) => obj.label,
        setter: (obj, value) => (obj as ButtonWidgetData).label = value,
      ), 
      field<ButtonWidgetData,Font>('font',
        annotations: [
          DeclareProperty(group: "font")
        ],
        getter: (obj) => obj.font,
        setter: (obj, value) => (obj as ButtonWidgetData).font = value,
        isNullable: true
      ), 
      field<ButtonWidgetData,Color>('color',
        annotations: [
          DeclareProperty(group: "font")
        ],
        getter: (obj) => obj.color,
        setter: (obj, value) => (obj as ButtonWidgetData).color = value,
        isNullable: true
      ), 
      field<ButtonWidgetData,Insets>('padding',
        annotations: [
          DeclareProperty(group: "layout")
        ],
        getter: (obj) => obj.padding,
        setter: (obj, value) => (obj as ButtonWidgetData).padding = value,
        isNullable: true
      ), 
      field<ButtonWidgetData,String>('onClick',
        type: StringType().optional(),
        annotations: [
          DeclareProperty(group: "events", editor: CodeEditorBuilder)
        ],
        getter: (obj) => obj.onClick,
        setter: (obj, value) => (obj as ButtonWidgetData).onClick = value,
        isNullable: true
      )
    ],
  );

  type<ColumnWidgetData>(
    location: 'package:velix_editor/metadata/widgets/column.dart:8:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "column", group: "container", icon: "widget_column"),
      JsonSerializable(discriminator: "column", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "column"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const [])
    ],
    constructor: ({String type = "column", List<WidgetData> children = const []}) => ColumnWidgetData(type: type, children: children),
    fromMapConstructor: (Map<String,dynamic> args) => ColumnWidgetData(type: args['type'] as String? ?? "column", children: args['children'] as List<WidgetData>? ?? const []),
    fromArrayConstructor: (List<dynamic> args) => ColumnWidgetData(type: args[0] as String? ?? "column", children: args[1] as List<WidgetData>? ?? const []),
  );

  type<GridWidgetData>(
    location: 'package:velix_editor/metadata/widgets/grid.dart:8:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "grid", group: "container", icon: "widget_grid"),
      JsonSerializable(discriminator: "grid", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "grid"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const [])
    ],
    constructor: ({String type = "grid", List<WidgetData> children = const []}) => GridWidgetData(type: type, children: children),
    fromMapConstructor: (Map<String,dynamic> args) => GridWidgetData(type: args['type'] as String? ?? "grid", children: args['children'] as List<WidgetData>? ?? const []),
    fromArrayConstructor: (List<dynamic> args) => GridWidgetData(type: args[0] as String? ?? "grid", children: args[1] as List<WidgetData>? ?? const []),
  );

  type<RowWidgetData>(
    location: 'package:velix_editor/metadata/widgets/row.dart:8:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "row", group: "container", icon: "widget_row"),
      JsonSerializable(discriminator: "row", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "row"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const [])
    ],
    constructor: ({String type = "row", List<WidgetData> children = const []}) => RowWidgetData(type: type, children: children),
    fromMapConstructor: (Map<String,dynamic> args) => RowWidgetData(type: args['type'] as String? ?? "row", children: args['children'] as List<WidgetData>? ?? const []),
    fromArrayConstructor: (List<dynamic> args) => RowWidgetData(type: args[0] as String? ?? "row", children: args[1] as List<WidgetData>? ?? const []),
  );

  type<StackWidgetData>(
    location: 'package:velix_editor/metadata/widgets/stack.dart:8:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "stack", group: "container", icon: "widget_stack"),
      JsonSerializable(discriminator: "stack", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "stack"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const [])
    ],
    constructor: ({String type = "stack", List<WidgetData> children = const []}) => StackWidgetData(type: type, children: children),
    fromMapConstructor: (Map<String,dynamic> args) => StackWidgetData(type: args['type'] as String? ?? "stack", children: args['children'] as List<WidgetData>? ?? const []),
    fromArrayConstructor: (List<dynamic> args) => StackWidgetData(type: args[0] as String? ?? "stack", children: args[1] as List<WidgetData>? ?? const []),
  );

  type<SwitchWidgetData>(
    location: 'package:velix_editor/metadata/widgets/switch.dart:8:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "switch", group: "widgets", icon: "widget_switch"),
      JsonSerializable(discriminator: "switch", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "switch"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const []), 
      param<String>('label', isNamed: true, isRequired: true), 
      param<String>('databinding', isNamed: true, isNullable: true, defaultValue: null)
    ],
    constructor: ({String type = "switch", List<WidgetData> children = const [], String label = '', String databinding = ''}) => SwitchWidgetData(type: type, children: children, label: label, databinding: databinding),
    fromMapConstructor: (Map<String,dynamic> args) => SwitchWidgetData(type: args['type'] as String? ?? "switch", children: args['children'] as List<WidgetData>? ?? const [], label: args['label'] as String? ?? '', databinding: args['databinding'] as String? ?? ''),
    fromArrayConstructor: (List<dynamic> args) => SwitchWidgetData(type: args[0] as String? ?? "switch", children: args[1] as List<WidgetData>? ?? const [], label: args[2] as String? ?? '', databinding: args[3] as String? ?? ''),
    fields: [
      field<SwitchWidgetData,String>('label',
        annotations: [
          DeclareProperty(group: "general")
        ],
        getter: (obj) => obj.label,
        setter: (obj, value) => (obj as SwitchWidgetData).label = value,
      ), 
      field<SwitchWidgetData,String>('databinding',
        type: StringType().optional(),
        annotations: [
          DeclareProperty(group: "general", editor: CodeEditorBuilder)
        ],
        getter: (obj) => obj.databinding,
        setter: (obj, value) => (obj as SwitchWidgetData).databinding = value,
        isNullable: true
      )
    ],
  );

  type<TextWidgetData>(
    location: 'package:velix_editor/metadata/widgets/text.dart:8:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "text", group: "widgets", icon: "widget_text"),
      JsonSerializable(discriminator: "text", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "text"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const []), 
      param<String>('label', isNamed: true, isRequired: true), 
      param<String>('databinding', isNamed: true, isRequired: true)
    ],
    constructor: ({String type = "text", List<WidgetData> children = const [], String label = '', String databinding = ''}) => TextWidgetData(type: type, children: children, label: label, databinding: databinding),
    fromMapConstructor: (Map<String,dynamic> args) => TextWidgetData(type: args['type'] as String? ?? "text", children: args['children'] as List<WidgetData>? ?? const [], label: args['label'] as String? ?? '', databinding: args['databinding'] as String? ?? ''),
    fromArrayConstructor: (List<dynamic> args) => TextWidgetData(type: args[0] as String? ?? "text", children: args[1] as List<WidgetData>? ?? const [], label: args[2] as String? ?? '', databinding: args[3] as String? ?? ''),
    fields: [
      field<TextWidgetData,String>('label',
        annotations: [
          DeclareProperty(group: "general")
        ],
        getter: (obj) => obj.label,
        setter: (obj, value) => (obj as TextWidgetData).label = value,
      ), 
      field<TextWidgetData,String>('databinding',
        type: StringType().optional(),
        annotations: [
          DeclareProperty(group: "general", editor: CodeEditorBuilder)
        ],
        getter: (obj) => obj.databinding,
        setter: (obj, value) => (obj as TextWidgetData).databinding = value,
        isNullable: true
      )
    ],
  );

  type<BooleanEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/bool_editor.dart:10:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => BooleanEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => BooleanEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => BooleanEditorBuilder(),
    methods: [
      method<BooleanEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as BooleanEditorBuilder).setup(args[1])
      )
    ],
  );

  type<CodeEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/code_editor.dart:13:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => CodeEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => CodeEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => CodeEditorBuilder(),
    methods: [
      method<CodeEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as CodeEditorBuilder).setup(args[1])
      )
    ],
  );

  type<ColorEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/color_editor.dart:10:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => ColorEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => ColorEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => ColorEditorBuilder(),
    methods: [
      method<ColorEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ColorEditorBuilder).setup(args[1])
      )
    ],
  );

  type<FontEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/font_editor.dart:10:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => FontEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => FontEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => FontEditorBuilder(),
    methods: [
      method<FontEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as FontEditorBuilder).setup(args[1])
      )
    ],
  );

  type<FontStyleEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/font_style_editor.dart:9:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => FontStyleEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => FontStyleEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => FontStyleEditorBuilder(),
    methods: [
      method<FontStyleEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as FontStyleEditorBuilder).setup(args[1])
      )
    ],
  );

  type<FontWeightEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/font_weight_editor.dart:9:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => FontWeightEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => FontWeightEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => FontWeightEditorBuilder(),
    methods: [
      method<FontWeightEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as FontWeightEditorBuilder).setup(args[1])
      )
    ],
  );

  type<IntEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/int_editor.dart:10:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => IntEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => IntEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => IntEditorBuilder(),
    methods: [
      method<IntEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as IntEditorBuilder).setup(args[1])
      )
    ],
  );

  type<PaddingEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/paddding_editor.dart:13:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => PaddingEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => PaddingEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => PaddingEditorBuilder(),
    methods: [
      method<PaddingEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as PaddingEditorBuilder).setup(args[1])
      )
    ],
  );

  type<StringEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/string_editor.dart:9:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => StringEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => StringEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => StringEditorBuilder(),
    methods: [
      method<StringEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as StringEditorBuilder).setup(args[1])
      )
    ],
  );

  type<ValueEditorBuilder>(
    location: 'package:velix_editor/property_panel/editor/value_editor.dart:145:1',
    superClass: propertyEditorBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => ValueEditorBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => ValueEditorBuilder(),
    fromArrayConstructor: (List<dynamic> args) => ValueEditorBuilder(),
    methods: [
      method<ValueEditorBuilder,void>('setup',
        annotations: [
          Inject()
        ],
        parameters: [
          param<PropertyEditorBuilderFactory>('registry', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ValueEditorBuilder).setup(args[1])
      )
    ],
  );

  type<ButtonWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/button_widget.dart:12:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => ButtonWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => ButtonWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => ButtonWidgetBuilder(),
    methods: [
      method<ButtonWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ButtonWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<ButtonEditWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/button_widget.dart:55:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => ButtonEditWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => ButtonEditWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => ButtonEditWidgetBuilder(),
    methods: [
      method<ButtonEditWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ButtonEditWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<ColumnEditWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/column_widget.dart:15:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => ColumnEditWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => ColumnEditWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => ColumnEditWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<ColumnEditWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ColumnEditWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<ColumnWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/column_widget.dart:91:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => ColumnWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => ColumnWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => ColumnWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<ColumnWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ColumnWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<ContainerEditWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/container_widget.dart:16:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => ContainerEditWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => ContainerEditWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => ContainerEditWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<ContainerEditWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ContainerEditWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<ContainerWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/container_widget.dart:94:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => ContainerWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => ContainerWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => ContainerWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<ContainerWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as ContainerWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<GridEditWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/grid_widget.dart:15:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => GridEditWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => GridEditWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => GridEditWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<GridEditWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as GridEditWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<GridWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/grid_widget.dart:91:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => GridWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => GridWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => GridWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<GridWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as GridWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<LabelWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/label_widget.dart:12:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => LabelWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => LabelWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => LabelWidgetBuilder(),
    methods: [
      method<LabelWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as LabelWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<EditLabelWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/label_widget.dart:93:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => EditLabelWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => EditLabelWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => EditLabelWidgetBuilder(),
    methods: [
      method<EditLabelWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditLabelWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<RowEditWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/row_widget.dart:15:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => RowEditWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => RowEditWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => RowEditWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<RowEditWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as RowEditWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<RowWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/row_widget.dart:91:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => RowWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => RowWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => RowWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<RowWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as RowWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<StackEditWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/stack_widget.dart:15:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => StackEditWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => StackEditWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => StackEditWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<StackEditWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as StackEditWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<StackWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/stack_widget.dart:91:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    params: [
      param<TypeRegistry>('typeRegistry', isNamed: true, isRequired: true)
    ],
    constructor: ({required TypeRegistry typeRegistry}) => StackWidgetBuilder(typeRegistry: typeRegistry),
    fromMapConstructor: (Map<String,dynamic> args) => StackWidgetBuilder(typeRegistry: args['typeRegistry'] as TypeRegistry),
    fromArrayConstructor: (List<dynamic> args) => StackWidgetBuilder(typeRegistry: args[0] as TypeRegistry),
    methods: [
      method<StackWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as StackWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<SwitchWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/switch_widget.dart:11:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => SwitchWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => SwitchWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => SwitchWidgetBuilder(),
    methods: [
      method<SwitchWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as SwitchWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<EditSwitchWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/switch_widget.dart:55:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => EditSwitchWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => EditSwitchWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => EditSwitchWidgetBuilder(),
    methods: [
      method<EditSwitchWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as EditSwitchWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<TextWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/text_widget.dart:11:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => TextWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => TextWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => TextWidgetBuilder(),
    methods: [
      method<TextWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as TextWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<TextEditWidgetBuilder>(
    location: 'package:velix_editor/theme/widgets/text_widget.dart:56:1',
    superClass: widgetBuilderDescriptor,
    annotations: [
      Injectable()
    ],
    constructor: () => TextEditWidgetBuilder(),
    fromMapConstructor: (Map<String,dynamic> args) => TextEditWidgetBuilder(),
    fromArrayConstructor: (List<dynamic> args) => TextEditWidgetBuilder(),
    methods: [
      method<TextEditWidgetBuilder,void>('setThema',
        annotations: [
          Inject()
        ],
        parameters: [
          param<WidgetFactory>('theme', isRequired: true)
        ],
        invoker: (List<dynamic> args)=> (args[0] as TextEditWidgetBuilder).setThema(args[1])
      )
    ],
  );

  type<LabelWidgetData>(
    location: 'package:velix_editor/metadata/widgets/label.dart:9:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "label", group: "widgets", icon: "widget_label"),
      JsonSerializable(discriminator: "label", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "text"), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const []), 
      param<String>('label', isNamed: true, isRequired: true), 
      param<Value>('value', isNamed: true, isRequired: true), 
      param<Font>('font', isNamed: true, isNullable: true, defaultValue: null), 
      param<String>('databinding', isNamed: true, isNullable: true, defaultValue: null)
    ],
    constructor: ({String type = "text", List<WidgetData> children = const [], String label = '', required Value value, required Font font, String databinding = ''}) => LabelWidgetData(type: type, children: children, label: label, value: value, font: font, databinding: databinding),
    fromMapConstructor: (Map<String,dynamic> args) => LabelWidgetData(type: args['type'] as String? ?? "text", children: args['children'] as List<WidgetData>? ?? const [], label: args['label'] as String? ?? '', value: args['value'] as Value, font: args['font'] as Font?, databinding: args['databinding'] as String? ?? ''),
    fromArrayConstructor: (List<dynamic> args) => LabelWidgetData(type: args[0] as String? ?? "text", children: args[1] as List<WidgetData>? ?? const [], label: args[2] as String? ?? '', value: args[3] as Value, font: args[4] as Font?, databinding: args[5] as String? ?? ''),
    fields: [
      field<LabelWidgetData,String>('label',
        annotations: [
          DeclareProperty(group: "general")
        ],
        getter: (obj) => obj.label,
        setter: (obj, value) => (obj as LabelWidgetData).label = value,
      ), 
      field<LabelWidgetData,Font>('font',
        annotations: [
          DeclareProperty(group: "general")
        ],
        getter: (obj) => obj.font,
        setter: (obj, value) => (obj as LabelWidgetData).font = value,
        isNullable: true
      ), 
      field<LabelWidgetData,String>('databinding',
        type: StringType().optional(),
        annotations: [
          DeclareProperty(group: "general", editor: CodeEditorBuilder)
        ],
        getter: (obj) => obj.databinding,
        setter: (obj, value) => (obj as LabelWidgetData).databinding = value,
        isNullable: true
      ), 
      field<LabelWidgetData,Value>('value',
        annotations: [
          DeclareProperty(group: "general")
        ],
        getter: (obj) => obj.value,
        setter: (obj, value) => (obj as LabelWidgetData).value = value,
      )
    ],
  );

  type<ContainerWidgetData>(
    location: 'package:velix_editor/metadata/widgets/container.dart:9:1',
    superClass: widgetDataDescriptor,
    annotations: [
      DeclareWidget(name: "container", group: "container", icon: "widget_container"),
      JsonSerializable(discriminator: "container", includeNull: false)
    ],
    params: [
      param<String>('type', isNamed: true, isNullable: true, defaultValue: "container"), 
      param<Border>('border', isNamed: true, isNullable: true, defaultValue: null), 
      param<Insets>('margin', isNamed: true, isNullable: true, defaultValue: null), 
      param<Insets>('padding', isNamed: true, isNullable: true, defaultValue: null), 
      param<List<WidgetData>>('children', isNamed: true, isNullable: true, defaultValue: const [])
    ],
    constructor: ({String type = "container", required Border border, required Insets margin, required Insets padding, List<WidgetData> children = const []}) => ContainerWidgetData(type: type, border: border, margin: margin, padding: padding, children: children),
    fromMapConstructor: (Map<String,dynamic> args) => ContainerWidgetData(type: args['type'] as String? ?? "container", border: args['border'] as Border?, margin: args['margin'] as Insets?, padding: args['padding'] as Insets?, children: args['children'] as List<WidgetData>? ?? const []),
    fromArrayConstructor: (List<dynamic> args) => ContainerWidgetData(type: args[0] as String? ?? "container", border: args[1] as Border?, margin: args[2] as Insets?, padding: args[3] as Insets?, children: args[4] as List<WidgetData>? ?? const []),
    fields: [
      field<ContainerWidgetData,Border>('border',
        getter: (obj) => obj.border,
        setter: (obj, value) => (obj as ContainerWidgetData).border = value,
        isNullable: true
      ), 
      field<ContainerWidgetData,Insets>('padding',
        getter: (obj) => obj.padding,
        setter: (obj, value) => (obj as ContainerWidgetData).padding = value,
        isNullable: true
      ), 
      field<ContainerWidgetData,Insets>('margin',
        getter: (obj) => obj.margin,
        setter: (obj, value) => (obj as ContainerWidgetData).margin = value,
        isNullable: true
      )
    ],
  );

  TypeDescriptor.verify();
}
