// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

import 'package:velix/velix.dart';
import 'package:app/main.dart' show ApplicationModule;
import 'package:velix_di/di/di.dart' show Module;
import 'package:velix_editor/editor_module.dart';

void registerTypes() {
  type<ApplicationModule>(
    location: 'package:app/main.dart:34:1',
    annotations: [
      Module(imports: [EditorModule])
    ],
    constructor: () => ApplicationModule(),
    fromMapConstructor: (Map<String,dynamic> args) => ApplicationModule(),
    fromArrayConstructor: (List<dynamic> args) => ApplicationModule(),
  );

  TypeDescriptor.verify();
}
