// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by velix registry builder
// ignore_for_file: unnecessary_import, unused_local_variable

import 'package:velix/velix.dart';
import 'package:sample/main.dart';
import 'package:sample/models/todo.dart';
import 'package:sample/providers/todo_provider.dart';
import 'package:sample/services/services.dart';
import 'package:velix/reflectable/reflectable.dart';
import 'package:velix_di/di/di.dart';

void registerAllDescriptors() {
  type<ApplicationModule>(
    location: 'package:sample/main.dart:51:1',
    annotations: [
      Module(imports: [])
    ],
    constructor: () => ApplicationModule(),
    fromArrayConstructor: (List<dynamic> args) => ApplicationModule(),
    methods: [
      method<ApplicationModule,void>('onInit',
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ApplicationModule).onInit()
      ), 
      method<ApplicationModule,void>('onDestroy',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as ApplicationModule).onDestroy()
      )
    ],
  );

  var DetailsDescriptor =  type<Details>(
    location: 'package:sample/models/todo.dart:3:1',
    params: [
      param<String>('author', isNamed: true, isRequired: true), 
      param<int>('priority', isNamed: true, isRequired: true), 
      param<DateTime>('date', isNamed: true, isRequired: true)
    ],
    constructor: ({String author = '', int priority = 0, required DateTime date}) => Details(author: author, priority: priority, date: date),
    fromArrayConstructor: (List<dynamic> args) => Details(author: args[0] as String? ?? '', priority: args[1] as int? ?? 0, date: args[2] as DateTime),
    fields: [
      field<Details,String>('author',
        type: StringType().maxLength(7),
        getter: (obj) => obj.author,
      ), 
      field<Details,int>('priority',
        type: IntType().greaterThan(0),
        getter: (obj) => obj.priority,
      ), 
      field<Details,DateTime>('date',
        getter: (obj) => obj.date,
      )
    ]
  );

  type<TestData>(
    location: 'package:sample/models/todo.dart:35:1',
    params: [
      param<String>('string_data', isNamed: true, isRequired: true), 
      param<int>('int_data', isNamed: true, isRequired: true), 
      param<int>('slider_int_data', isNamed: true, isRequired: true), 
      param<bool>('bool_data', isNamed: true, isRequired: true), 
      param<DateTime>('datetime_data', isNamed: true, isRequired: true)
    ],
    constructor: ({String string_data = '', int int_data = 0, int slider_int_data = 0, bool bool_data = false, required DateTime datetime_data}) => TestData(string_data: string_data, int_data: int_data, slider_int_data: slider_int_data, bool_data: bool_data, datetime_data: datetime_data),
    fromArrayConstructor: (List<dynamic> args) => TestData(string_data: args[0] as String? ?? '', int_data: args[1] as int? ?? 0, slider_int_data: args[2] as int? ?? 0, bool_data: args[3] as bool? ?? false, datetime_data: args[4] as DateTime),
    fields: [
      field<TestData,String>('string_data',
        type: StringType().maxLength(7),
        getter: (obj) => obj.string_data,
        setter: (obj, value) => (obj as TestData).string_data = value,
      ), 
      field<TestData,int>('int_data',
        type: IntType().greaterThan(0),
        getter: (obj) => obj.int_data,
        setter: (obj, value) => (obj as TestData).int_data = value,
      ), 
      field<TestData,int>('slider_int_data',
        type: IntType().greaterThan(0),
        getter: (obj) => obj.slider_int_data,
        setter: (obj, value) => (obj as TestData).slider_int_data = value,
      ), 
      field<TestData,bool>('bool_data',
        getter: (obj) => obj.bool_data,
        setter: (obj, value) => (obj as TestData).bool_data = value,
      ), 
      field<TestData,DateTime>('datetime_data',
        getter: (obj) => obj.datetime_data,
      )
    ]
  );

  var TodoServiceDescriptor =  type<TodoService>(
    location: 'package:sample/services/services.dart:3:1',
    annotations: [
      Injectable()
    ],
    constructor: () => TodoService(),
    fromArrayConstructor: (List<dynamic> args) => TodoService(),
    methods: [
      method<TodoService,void>('onInit',
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as TodoService).onInit()
      ), 
      method<TodoService,void>('onDestroy',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as TodoService).onDestroy()
      )
    ],
  );

  type<PerWidgetState>(
    location: 'package:sample/services/services.dart:18:1',
    annotations: [
      Injectable(scope: "environment")
    ],
    constructor: () => PerWidgetState(),
    fromArrayConstructor: (List<dynamic> args) => PerWidgetState(),
    methods: [
      method<PerWidgetState,void>('onInit',
        annotations: [
          OnInit()
        ],
        invoker: (List<dynamic> args)=> (args[0] as PerWidgetState).onInit()
      ), 
      method<PerWidgetState,void>('onDestroy',
        annotations: [
          OnDestroy()
        ],
        invoker: (List<dynamic> args)=> (args[0] as PerWidgetState).onDestroy()
      )
    ],
  );

  type<Todo>(
    location: 'package:sample/models/todo.dart:17:1',
    params: [
      param<String>('id', isNamed: true, isRequired: true), 
      param<String>('title', isNamed: true, isRequired: true), 
      param<Details>('details', isNamed: true, isNullable: true, defaultValue: null), 
      param<bool>('completed', isNamed: true, isNullable: true, defaultValue: false)
    ],
    constructor: ({String id = '', String title = '', required Details details, bool completed = false}) => Todo(id: id, title: title, details: details, completed: completed),
    fromArrayConstructor: (List<dynamic> args) => Todo(id: args[0] as String? ?? '', title: args[1] as String? ?? '', details: args[2] as Details, completed: args[3] as bool? ?? false),
    fields: [
      field<Todo,String>('id',
        type: StringType().maxLength(7),
        getter: (obj) => obj.id,
        setter: (obj, value) => (obj as Todo).id = value,
      ), 
      field<Todo,String>('title',
        type: StringType().maxLength(10),
        getter: (obj) => obj.title,
        setter: (obj, value) => (obj as Todo).title = value,
      ), 
      field<Todo,bool>('completed',
        getter: (obj) => obj.completed,
        setter: (obj, value) => (obj as Todo).completed = value,
      ), 
      field<Todo,Details>('details',
        getter: (obj) => obj.details,
        setter: (obj, value) => (obj as Todo).details = value,
        isNullable: true
      )
    ]
  );

  type<TodoProvider>(
    location: 'package:sample/providers/todo_provider.dart:6:1',
    annotations: [
      Injectable()
    ],
    params: [
      param<TodoService>('todoService', isNamed: true, isRequired: true)
    ],
    constructor: ({required TodoService todoService}) => TodoProvider(todoService: todoService),
    fromArrayConstructor: (List<dynamic> args) => TodoProvider(todoService: args[0] as TodoService),
  );

}
