name: velix_di
description: "a flutter dependency injection framework that implements containers that assemble and control object lifecycle as in spring."
version: 1.0.1

homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.8"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  #path_provider: ^2.1.5
  stack_trace: ^1.10.0
  path: ^1.9.1
  #provider: ^6.0.0
  intl: ^0.20.2
  source_gen: ^3.0.0
  analyzer: '^8.0.0'
  build: ^3.0.0
  glob: ^2.1.3
  velix: ^0.91.0

dev_dependencies:
  build_runner: ^2.4.7
  #test: ^1.25.0
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
