targets:
  $default:
    sources:
      - example/**
      - lib/**
      - $package$
    builders:
      velix|registry_builder:
        options:
          package: "velix_mapper/"
        generate_for:
          - example/*.dart
          - example/**/*.dart
          - "!example/**/*.g.dart"
          - "!example/**/*.part.dart"
      velix|registry_aggregator:
        options:
          prefix: "example"
        generate_for:
          - example/main.dart
  test:
    sources:
      - test/**
    builders:
      velix|registry_builder:
        generate_for:
          - test/*.dart
          - test/**/*.dart
          - "!test/**/*.g.dart"
          - "!test/**/*.part.dart"
      velix|registry_aggregator:
        options:
          prefix: "test"
          generate_for:
            - test/model.dart