builders:
  type_builder:
    import: "package:velix/src/generators/type_generator.dart"
    builder_factories: [ "typeBuilder" ]
    build_extensions: { "$lib$": [ ".type_registry.g.dart" ] }
    auto_apply: none
    build_to: source
    defaults:
      options:
        function_name: "registerAllDescriptors"
        part_of: ""

targets:
  $default:
    builders:
  test:
    sources:
      - test/**
    builders:
      velix|registry_builder:
        generate_for:
          - test/*.dart
          - test/**/*.dart
          - "!test/**/*.g.dart"
          - "!test/**/*.part.dart"

      velix|registry_aggregator:
        options:
          prefix: "test"
        generate_for:
          - test/model.dart
      #velix|type_builder:
      #  generate_for:
      #    include:
      #      - test/model.dart
      #    exclude:
      #      - test/**.g.dart