targets:
  $default:
    builders:
      velix|command_builder:
        generate_for:
          include:
            - lib/**/*.dart

      velix|type_builder:
        generate_for:
          include:
            - lib/main.dart
