name: editor_sample
description: "velix editor sample."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.8"

dependencies:
  build_runner: ^2.4.7
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  flutter:
    sdk: flutter
  provider: ^6.0.0
  build: ^3.0.0
  easy_localization: ^3.0.8
  cupertino_icons: ^1.0.8
  velix: ^0.91.1
  velix_di: ^1.0.2
  velix_mapper: ^1.1.2
  velix_i18n: ^1.0.1
  velix_ui: ^1.1.2
  velix_editor: ^0.1.1
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  flutter_code_editor: ^0.3.3
  expressions: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  glob: ^2.1.3

flutter:
  assets:
    - assets/locales/en/sample.json
    - assets/locales/de/sample.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true