name: velix_editor_sample
description: "Velix UI runtime sample."

homepage: https://github.com/coolsamson7/velix
repository: https://github.com/coolsamson7/velix

resolution: workspace
version: 0.1.3

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.8"

dependencies:
  build_runner: ^2.4.7
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  flutter:
    sdk: flutter
  provider: ^6.0.0
  build: ^3.0.0
  easy_localization: ^3.0.8
  cupertino_icons: ^1.0.8
  velix: ^0.91.3
  velix_di: ^1.1.1
  velix_mapper: ^1.2.1
  velix_i18n: ^1.2.0
  velix_ui: ^1.3.0
  velix_editor: ^0.1.3
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  flutter_code_editor: ^0.3.3
  expressions: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  glob: ^2.1.3

flutter:
  assets:
    - assets/locales/en/
    - assets/screens/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true