name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0' # Dart 3.9.x
          channel: 'stable'
          cache: true  # Enables Flutter SDK caching for faster builds

      - name: Bootstrap Melos workspace
        run: dart pub global activate melos && melos bootstrap

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze || true

      - name: Run tests
        run: melos exec --dir-exists=test -- "flutter test"
