name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' # This one has Dart >= 3.8.1
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze || true

      - name: Run tests
        run: flutter test

      - name: Publish to pub.dev
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          echo "$PUB_CREDENTIALS" > ~/.pub-cache/credentials.json
          flutter pub publish --force
